### ISSUE TITLE
Integrate a link to Wii.guide into the landing page

### ISSUE THREAD

**Issue by sks316** [hacks-guide/Guide_Landing#11]
The people at RiiConnect24 have written a great guide for Wii hacking, from stock to Homebrew Channel, cIOS, RiiConnect24, and Wiimmfi. It's a really good guide and I feel it should be incorporated into the landing page.

**Comment by Plailect** [comment]
I'll take a look at it.

**Comment by Xenthio** [comment]
any update? this should be done.

**Comment by DanHolli123** [comment]
Another bump, it's been awhile but not much has changed in the scene

**Comment by BroJac5246** [comment]
I'm not sure if this will ever be added, but it definitely should! Wii.guide is very high-quality and is similar to what is on hacks.guide.

**Comment by bor-real** [comment]
Since the creation of wii.hacks.guide, this is no longer neccesary.
