### ISSUE TITLE
Any plans to extend this to non-gaming devices?

### ISSUE THREAD

**Issue by upintheairsheep** [hacks-guide/Guide_Landing#45]
Hello, are *.hacks.guide sites for non-gaming devices such as iOS devices, Android devices, Smart TVs, iPods, and more in scope?

**Comment by ihaveamac** [comment]
Probably not since our overall experience is limited to a select few devices, and there are better websites for other devices.

**Comment by upintheairsheep** [comment]
> Probably not since our overall experience is limited to a select few devices, and there are better websites for other devices.

But are they on scope if a guide is needed?

**Comment by ihaveamac** [comment]
Unlikely if there are already much better guides for those other devices. iOS and Android jailbreaking and rooting have significantly larger scenes than game consoles so there's already a ton more people working on them.

**Comment by upintheairsheep** [comment]
> Unlikely if there are already much better guides for those other devices. iOS and Android jailbreaking and rooting have significantly larger scenes than game consoles so there's already a ton more people working on them.

Just discovered cfw.guide which does non-gaming devices along with gaming devices.
