### ISSUE TITLE
Feature request: PS4 hacks guide

### ISSUE THREAD

**Issue by imide** [hacks-guide/Guide_Landing#48]
right now, the PS4 jailbreak scene is flourishing as a new jailbreak was discovered for basically most firmware. (1.0.0 essentially to 11.0.0, most recent is 11.5.0)

also its really hard to know which data is accurate and up to date for ps4 homebrewing. its a shit show

**Comment by playerjmr** [comment]
> right now, the PS4 jailbreak scene is flourishing as a new jailbreak was discovered for basically most firmware. (1.0.0 essentially to 11.0.0, most recent is 11.5.0)
> 
> also its really hard to know which data is accurate and up to date for ps4 homebrewing. its a shit show

I would ask the cfw.guide people as this does not fall under the “Nintendo homebrew” category.

**Comment by ihaveamac** [comment]
Probably not because our experience is with Nintendo consoles. (If you're wondering why we have Vita, it's from the previous owner and operates outside of NH.)
